### ISSUE TITLE
Not showing devices

### ISSUE THREAD

**Issue by Rallo00** [Raptor007/Falcon4toSaitek#1]
Hi, I followed al the guide to set up this tool but when I open it no devices are shown. Any idea on how to fix it? Drivers are correctly installed and the mfd extractor works like a charm. 

Thanks. Hope you will make a new version of it.

**Comment by Raptor007** [comment]
Have you tried the "Restart DirectOutput" button in bottom left?  Are you getting a "Failed to initialized DirectOutput!" dialog?

It has been a while since I've used or worked on this project, but I would like to update it and fix some things.

**Comment by Raptor007** [comment]
I *think* I see what's happening here.  The code provided by Saitek looks in the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Saitek\DirectOutput` to find where DirectOutput.dll is installed:

https://github.com/Raptor007/Falcon4toSaitek/blob/ad8ad89d3a450f9017d81fe1d2f082a7dee6d332/Raptor007's%20Falcon%204%20to%20Saitek%20Utility/DirectOutputImpl.cpp#L241

I'm guessing you're running Windows 64-bit.  My application is 32-bit.  In theory that's not a problem.  It just means the registry location would be redirected to `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Saitek\DirectOutput` which should point to a 32-bit version of DirectOutput.dll for 32-bit software to utilize.  However, using the latest drivers, this key does not exist!  I assume someone at Logitech didn't consider that we might still run 32-bit software targeting DirectOutput on a 64-bit system.

I'll work on a 64-bit build of my program and see if that solves the problem.  (There's a good chance I'll also need to clean up some thread locking and/or resource de-allocation issues for stability, as I seem to recall the application would randomly die after running for a while.)

**Comment by Rallo00** [comment]
Thank you @Raptor007 that would be amazing. No workaround or software has been made on the internet to do what this tool does, it's unique. Hope it will work soon!

**Comment by Raptor007** [comment]
@Rallo00  Sorry for the long wait!  I've been busy, and my 64-bit build just doesn't want to run.  Seems like it might be related to the .NET manifests, but I haven't messed with that in years.

Today I tried a different approach: getting the 32-bit DLLs installed alongside the 64-bit, like the old Saitek drivers did.

I installed the latest 32-bit Saitek DirectOutput onto a virtual machine, then copied its "C:\Program Files\Logitech\DirectOutput" directory into "C:\Program Files (x86)" on my 64-bit Windows install, and adapted the Saitek registry keys into `Wow6432Node` where 32-bit software looks for them.

This seems to work!  Now my program can detect devices again.

I've attached the necessary files here: [DirectOutput 8.0.213.0 32-bit.zip](https://github.com/Raptor007/Falcon4toSaitek/files/14234331/DirectOutput.8.0.213.0.32-bit.zip)

Extract this zip such that you end up with "C:\Program Files (x86)\Logitech\DirectOutput" containing the DLLs, then double-click "Saitek DirectOutput x86.reg" to add the necessary `Wo6432Node\Saitek` registry keys.  (You may want to first check it with a text editor to be make sure the paths are correct.)

Note that you should not be replacing any files!!  Your 64-bit DirectOutput should continue to live under "C:\Program Files" and this 32-bit install should be in "C:\Program Files (x86)".  Both sets of DLLs communicate with the 64-bit DirectOutput service.

Let me know if this method works for you too.

**Comment by Rallo00** [comment]
Hi @Raptor007, thanks for your feedback and sorry for the late reply. Much appreciated. In the weekend I will have some time and I'll test it out.
Will get back to you soon.

**Comment by omaemaru** [comment]
Works for me

**Comment by Rallo00** [comment]
Same here. Thanks for bringing them back to life!! @Raptor007
